### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mavericksy** [Narthorn/gpg-bruteforce#2]
great script.
For anybody using it, maybe quoting the $pass variable in bf.sh if your password has spaces.
Add --batch to the $gpg_test for v2 gpg

**Comment by Narthorn** [comment]
Thanks! I fixed that quoting issue.

I couldn't find a problem with omitting --batch for gpg v2 on my arch install, so I left that one out still - it's probably fine to have it, but I don't really want to add it unless I can repro the issue.
